<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>left-click.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="left-click.ico" />
	</ItemGroup>
</Project>